name: CI for Pull Requests to Develop

# develop 브랜치로 PR이 생성되거나 업데이트될 때만 실행
on:
  pull_request:
    branches:
      - develop  # develop 브랜치로의 PR에 대해서만 실행

jobs:
  build:

    # GitHub 제공 가상 환경 사용
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # Java 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # 의존성 설치 및 빌드 실행 (Gradle)
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # 테스트 실행
      - name: Run tests
        run: ./gradlew test --no-daemon

      # 빌드와 테스트 후, 결과 보고
      - name: Show test results
        if: failure()  # 빌드나 테스트가 실패했을 때만 실행
        run: cat build/reports/tests/test/index.html || true
